In [1]:
pip install boxmot motmetrics

Collecting boxmot
  Downloading boxmot-21.0.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: motmetrics in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (1.4.0)
Collecting click>=8.1.8 (from boxmot)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filterpy<2.0.0,>=1.4.5 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (1.4.5)
Collecting ftfy<7.0.0,>=6.1.3 (from boxmot)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting gdown<6.0.0,>=5.1.0 (from boxmot)
  Downloading gdown-5.2.2-py3-none-any.whl.metadata (5.8 kB)
Collecting huggingface-hub>=1.7.1 (from boxmot)
  Downloading huggingface_hub-1.18.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: lapx<1.0.0,>=0.5.5 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (0.9.4)
Requirement already satisfied: numpy>=2.2.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (2.2.6)
Requirement already satisfied: opencv-python<5.0.0,>=4.7.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (4.13.0.92)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (2.3.3)
Collecting regex>=2024.0.0 (from boxmot)
  Downloading regex-2026.5.9-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting rich>=15.0.0 (from boxmot)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting scikit-learn<2.0.0,>=1.3.0 (from boxmot)
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: torch<3.0.0,>=2.2.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (2.5.1+cu121)
Requirement already satisfied: torchvision<1.0.0,>=0.17.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from boxmot) (0.20.1+cu121)
Collecting yacs<1.0.0,>=0.1.8 (from boxmot)
  Downloading yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: scipy in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from filterpy<2.0.0,>=1.4.5->boxmot) (1.15.3)
Requirement already satisfied: matplotlib in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from filterpy<2.0.0,>=1.4.5->boxmot) (3.10.9)
Requirement already satisfied: wcwidth in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from ftfy<7.0.0,>=6.1.3->boxmot) (0.7.0)
Collecting beautifulsoup4 (from gdown<6.0.0,>=5.1.0->boxmot)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: filelock in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from gdown<6.0.0,>=5.1.0->boxmot) (3.29.0)
Requirement already satisfied: requests[socks] in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from gdown<6.0.0,>=5.1.0->boxmot) (2.33.1)
Requirement already satisfied: tqdm in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from gdown<6.0.0,>=5.1.0->boxmot) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from pandas<3.0.0,>=2.0.0->boxmot) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from pandas<3.0.0,>=2.0.0->boxmot) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from pandas<3.0.0,>=2.0.0->boxmot) (2026.2)
Collecting joblib>=1.2.0 (from scikit-learn<2.0.0,>=1.3.0->boxmot)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<2.0.0,>=1.3.0->boxmot)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torch<3.0.0,>=2.2.1->boxmot) (4.15.0)
Requirement already satisfied: networkx in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torch<3.0.0,>=2.2.1->boxmot) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torch<3.0.0,>=2.2.1->boxmot) (3.1.6)
Requirement already satisfied: fsspec in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torch<3.0.0,>=2.2.1->boxmot) (2026.4.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torch<3.0.0,>=2.2.1->boxmot) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from sympy==1.13.1->torch<3.0.0,>=2.2.1->boxmot) (1.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from torchvision<1.0.0,>=0.17.1->boxmot) (12.2.0)
Requirement already satisfied: PyYAML in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from yacs<1.0.0,>=0.1.8->boxmot) (6.0.3)
Requirement already satisfied: xmltodict>=0.12.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from motmetrics) (1.0.4)
Requirement already satisfied: colorama in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from click>=8.1.8->boxmot) (0.4.6)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub>=1.7.1->boxmot)
  Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=1.7.1->boxmot)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: packaging>=20.9 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from huggingface-hub>=1.7.1->boxmot) (26.0)
Collecting typer<0.26.0,>=0.20.0 (from huggingface-hub>=1.7.1->boxmot)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: certifi in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot) (2026.4.22)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot) (3.13)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting shellingham>=1.3.0 (from typer<0.26.0,>=0.20.0->huggingface-hub>=1.7.1->boxmot)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting annotated-doc>=0.0.2 (from typer<0.26.0,>=0.20.0->huggingface-hub>=1.7.1->boxmot)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: six>=1.5 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->boxmot) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=15.0.0->boxmot)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from rich>=15.0.0->boxmot) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=15.0.0->boxmot)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=1.7.1->boxmot) (1.3.1)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->gdown<6.0.0,>=5.1.0->boxmot)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from jinja2->torch<3.0.0,>=2.2.1->boxmot) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot) (1.5.0)
Requirement already satisfied: pyparsing>=3 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\vamseekrishna.p\miniconda3\envs\aerial\lib\site-packages (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot) (2.6.3)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Downloading boxmot-21.0.0-py3-none-any.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   --------------------- ------------------ 1.3/2.4 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 6.8 MB/s  0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Downloading gdown-5.2.2-py3-none-any.whl (18 kB)
Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Downloading yacs-0.1.8-py3-none-any.whl (14 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading huggingface_hub-1.18.0-py3-none-any.whl (684 kB)
   ---------------------------------------- 0.0/684.4 kB ? eta -:--:--
   ---------------------------------------- 684.4/684.4 kB 5.4 MB/s  0:00:00
Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   --------------- ------------------------ 1.6/4.0 MB 7.0 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.8 MB/s  0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading regex-2026.5.9-cp310-cp310-win_amd64.whl (278 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: yacs, threadpoolctl, soupsieve, shellingham, regex, PySocks, mdurl, joblib, hf-xet, h11, ftfy, click, annotated-doc, scikit-learn, markdown-it-py, httpcore, beautifulsoup4, anyio, rich, httpx, gdown, typer, huggingface-hub, boxmot

   ------ ---------------------------------  4/24 [regex]
   ----------- ----------------------------  7/24 [joblib]
   ----------- ----------------------------  7/24 [joblib]
   ------------- --------------------------  8/24 [hf-xet]
   ------------------ --------------------- 11/24 [click]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   --------------------- ------------------ 13/24 [scikit-learn]
   ----------------------- ---------------- 14/24 [markdown-it-py]
   ------------------------- -------------- 15/24 [httpcore]
   ---------------------------- ----------- 17/24 [anyio]
   ------------------------------ --------- 18/24 [rich]
   ------------------------------ --------- 18/24 [rich]
   ------------------------------ --------- 18/24 [rich]
   ------------------------------- -------- 19/24 [httpx]
   ------------------------------------ --- 22/24 [huggingface-hub]
   ------------------------------------ --- 22/24 [huggingface-hub]
   ------------------------------------ --- 22/24 [huggingface-hub]
   ------------------------------------ --- 22/24 [huggingface-hub]
   ------------------------------------ --- 22/24 [huggingface-hub]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   -------------------------------------- - 23/24 [boxmot]
   ---------------------------------------- 24/24 [boxmot]

Successfully installed PySocks-1.7.1 annotated-doc-0.0.4 anyio-4.13.0 beautifulsoup4-4.14.3 boxmot-21.0.0 click-8.4.1 ftfy-6.3.1 gdown-5.2.2 h11-0.16.0 hf-xet-1.5.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.18.0 joblib-1.5.3 markdown-it-py-4.2.0 mdurl-0.1.2 regex-2026.5.9 rich-15.0.0 scikit-learn-1.7.2 shellingham-1.5.4 soupsieve-2.8.4 threadpoolctl-3.6.0 typer-0.25.1 yacs-0.1.8
Note: you may need to restart the kernel to use updated packages.

In [3]:
import cv2
import time
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm import tqdm

from ultralytics import YOLO

import motmetrics as mm

In [38]:
from ultralytics import YOLO


# -------------------------------
# YOLO11s COCO pretrained baseline
# -------------------------------
model_base = YOLO(
    "yolo11s.pt"
)

model_base.fuse()



# -------------------------------
# YOLO11s VisDrone fine-tuned
# -------------------------------
model_ft = YOLO(
    r"C:\Users\VAMSEEKRISHNA.P\Desktop\assignment\runs\detect\runs\YOLO11s_VisDrone_1280\weights\best.pt"
)

model_ft.fuse()

YOLO11s summary (fused): 100 layers, 9,443,760 parameters, 0 gradients, 21.5 GFLOPs
YOLO11s summary (fused): 101 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): C3k2(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(96, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(32, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (3): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (4): C3k2(
        (cv1): Conv(
          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (5): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (6): C3k2(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (7): Conv(
        (conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (8): C3k2(
        (cv1): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (9): SPPF(
        (cv1): Conv(
          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): Identity()
        )
        (cv2): Conv(
          (conv): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
      )
      (10): C2PSA(
        (cv1): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): Sequential(
          (0): PSABlock(
            (attn): Attention(
              (qkv): Conv(
                (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
              (proj): Conv(
                (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
              (pe): Conv(
                (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
                (act): Identity()
              )
            )
            (ffn): Sequential(
              (0): Conv(
                (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
            )
          )
        )
      )
      (11): Upsample(scale_factor=2.0, mode='nearest')
      (12): Concat()
      (13): C3k2(
        (cv1): Conv(
          (conv): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (14): Upsample(scale_factor=2.0, mode='nearest')
      (15): Concat()
      (16): C3k2(
        (cv1): Conv(
          (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (17): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (18): Concat()
      (19): C3k2(
        (cv1): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (20): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (21): Concat()
      (22): C3k2(
        (cv1): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (23): Detect(
        (cv2): ModuleList(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Conv(
              (conv): Conv2d(512, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (cv3): ModuleList(
          (0): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=512)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (dfl): DFL(
          (conv): Conv2d(16, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
        )
      )
    )
  )
)

In [39]:
VAL_ROOT = Path(
    r"C:\Users\VAMSEEKRISHNA.P\Desktop\assignment\VisDrone2019-MOT-val\VisDrone2019-MOT-val"
)

SEQ_DIR = VAL_ROOT / "sequences"

ANN_DIR = VAL_ROOT / "annotations"


sequences = sorted(
    list(SEQ_DIR.iterdir())
)[:2]


print(
    "Testing sequences:"
)

for s in sequences:
    print(s.name)

Testing sequences:
uav0000086_00000_v
uav0000117_02622_v

In [26]:
def load_gt(seq_name):

    file = ANN_PATH / (seq_name+".txt")


    gt={}


    with open(file,"r") as f:


        for line in f:

            d=line.strip().split(",")


            frame=int(d[0])

            tid=int(d[1])


            x=float(d[2])
            y=float(d[3])
            w=float(d[4])
            h=float(d[5])


            cls=int(d[7])


            # persons only
            if cls not in [1,2]:
                continue


            if frame not in gt:
                gt[frame]=[]



            gt[frame].append(
                [
                    tid,
                    x,
                    y,
                    w,
                    h
                ]
            )


    return gt

In [27]:
def calc_iou(
    gt,
    pred
):


    gt_boxes=[
        g[1:]
        for g in gt
    ]

    pred_boxes=[
        p[1:]
        for p in pred
    ]


    return mm.distances.iou_matrix(

        np.asarray(
            gt_boxes,
            dtype=float
        ),

        np.asarray(
            pred_boxes,
            dtype=float
        ),

        max_iou=0.5
    )

In [43]:
def evaluate_tracker(detector, tracker_yaml):


    acc = mm.MOTAccumulator(
        auto_id=True
    )


    total_frames=0

    start=time.time()



    for seq in sequences:


        print(
            "Sequence:",
            seq.name
        )


        gt = load_gt(
            seq.name
        )


        frames = sorted(
            seq.glob("*.jpg")
        )


        # reset tracker memory
        detector.predictor=None



        for idx,img_path in enumerate(
            tqdm(frames)
        ):


            frame_id=idx+1


            frame=cv2.imread(
                str(img_path)
            )



            result= detector.track(

                frame,

                imgsz=1280,

                conf=0.05,

                classes=[0],

                tracker=tracker_yaml,

                persist=True,

                device=0,

                verbose=False

            )[0]



            preds=[]


            if result.boxes.id is not None:


                ids=result.boxes.id.cpu().numpy()

                boxes=result.boxes.xywh.cpu().numpy()



                for tid,box in zip(
                    ids,
                    boxes
                ):


                    x,y,w,h=box


                    preds.append(

                        [
                            int(tid),

                            x-w/2,

                            y-h/2,

                            w,

                            h
                        ]

                    )


            gt_frame = gt.get(
                frame_id,
                []
            )



            acc.update(

                [g[0] for g in gt_frame],

                [p[0] for p in preds],

                calc_iou(
                    gt_frame,
                    preds
                )

            )


            total_frames+=1



    fps = (
        total_frames /
        (time.time()-start)
    )


    return acc,fps

In [47]:
experiments = [

    {
        "name": "YOLO11s_Base_ByteTrack",
        "model": model_base,
        "tracker": r"Trackers\bytetrack_drone.yaml"
    },

    {
        "name": "YOLO11s_Base_BoTSORT_GMC",
        "model": model_base,
        "tracker": r"Trackers\botsort_gmc_drone.yaml"
    },


    {
        "name": "YOLO11s_FT_ByteTrack",
        "model": model_ft,
        "tracker": r"Trackers\bytetrack_drone.yaml"
    },

    {
        "name": "YOLO11s_FT_BoTSORT_GMC",
        "model": model_ft,
        "tracker": r"Trackers\botsort_gmc_drone.yaml"
    }

]

In [48]:
import cv2
import time
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm import tqdm

from ultralytics import YOLO

import motmetrics as mm


# -------------------------
# NumPy 2.0 patch
# -------------------------
if not hasattr(np, "asfarray"):
    np.asfarray = lambda x: np.asarray(x, dtype=float)

In [49]:
results=[]

mh=mm.metrics.create()


for exp in experiments:


    print(
        "\nRunning:",
        exp["name"]
    )


    acc,fps = evaluate_tracker(
        exp["model"],
        exp["tracker"]
    )


    summary = mh.compute(
        acc,
        metrics=[
            "mota",
            "idf1",
            "num_switches",
            "mostly_tracked",
            "mostly_lost",
            "precision",
            "recall"
        ],
        name="result"
    )


    results.append({

        "Pipeline":exp["name"],

        "FPS":fps,

        "MOTA":summary["mota"].iloc[0],

        "IDF1":summary["idf1"].iloc[0],

        "ID Switches":summary["num_switches"].iloc[0],

        "Mostly Tracked":summary["mostly_tracked"].iloc[0],

        "Mostly Lost":summary["mostly_lost"].iloc[0],

        "Precision":summary["precision"].iloc[0],

        "Recall":summary["recall"].iloc[0]

    })


df=pd.DataFrame(results)

df

Running: YOLO11s_Base_ByteTrack
Sequence: uav0000086_00000_v

100%|██████████| 464/464 [00:14<00:00, 31.35it/s]

Sequence: uav0000117_02622_v

100%|██████████| 349/349 [00:15<00:00, 22.65it/s]

Running: YOLO11s_Base_BoTSORT_GMC
Sequence: uav0000086_00000_v

100%|██████████| 464/464 [00:54<00:00,  8.56it/s]

Sequence: uav0000117_02622_v

100%|██████████| 349/349 [01:38<00:00,  3.55it/s]

Running: YOLO11s_FT_ByteTrack
Sequence: uav0000086_00000_v

100%|██████████| 464/464 [00:15<00:00, 30.25it/s]

Sequence: uav0000117_02622_v

100%|██████████| 349/349 [00:15<00:00, 22.20it/s]

Running: YOLO11s_FT_BoTSORT_GMC
Sequence: uav0000086_00000_v

100%|██████████| 464/464 [00:47<00:00,  9.78it/s]

Sequence: uav0000117_02622_v

100%|██████████| 349/349 [01:26<00:00,  4.04it/s]

,Pipeline,FPS,MOTA,IDF1,ID Switches,Mostly Tracked,Mostly Lost,Precision,Recall
0,YOLO11s_Base_ByteTrack,26.844614,0.198281,0.324777,38,6,102,0.870368,0.234387
1,YOLO11s_Base_BoTSORT_GMC,5.332247,0.176435,0.299997,8,7,101,0.862644,0.210149
2,YOLO11s_FT_ByteTrack,26.117115,0.405502,0.517980,228,23,56,0.787576,0.565097
3,YOLO11s_FT_BoTSORT_GMC,6.073024,0.287679,0.440554,27,17,84,0.837382,0.358065

In [50]:
results_df = pd.DataFrame(results)
results_df

,Pipeline,FPS,MOTA,IDF1,ID Switches,Mostly Tracked,Mostly Lost,Precision,Recall
0,YOLO11s_Base_ByteTrack,26.844614,0.198281,0.324777,38,6,102,0.870368,0.234387
1,YOLO11s_Base_BoTSORT_GMC,5.332247,0.176435,0.299997,8,7,101,0.862644,0.210149
2,YOLO11s_FT_ByteTrack,26.117115,0.405502,0.517980,228,23,56,0.787576,0.565097
3,YOLO11s_FT_BoTSORT_GMC,6.073024,0.287679,0.440554,27,17,84,0.837382,0.358065

In [51]:
from ultralytics import YOLO
import cv2
import time
import numpy as np
from pathlib import Path
from collections import defaultdict


# base COCO model
model_base = YOLO(
    "yolo11s.pt"
)


# fine tuned model
model_ft = YOLO(
    r"C:\Users\VAMSEEKRISHNA.P\Desktop\assignment\runs\detect\runs\YOLO11s_VisDrone_1280\weights\best.pt"
)


model_base.fuse()
model_ft.fuse()

YOLO11s summary (fused): 100 layers, 9,443,760 parameters, 0 gradients, 21.5 GFLOPs
YOLO11s summary (fused): 101 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (2): C3k2(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(96, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(32, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (3): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (4): C3k2(
        (cv1): Conv(
          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (5): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (6): C3k2(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (7): Conv(
        (conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (8): C3k2(
        (cv1): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (9): SPPF(
        (cv1): Conv(
          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): Identity()
        )
        (cv2): Conv(
          (conv): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
      )
      (10): C2PSA(
        (cv1): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): Sequential(
          (0): PSABlock(
            (attn): Attention(
              (qkv): Conv(
                (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
              (proj): Conv(
                (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
              (pe): Conv(
                (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
                (act): Identity()
              )
            )
            (ffn): Sequential(
              (0): Conv(
                (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
                (act): Identity()
              )
            )
          )
        )
      )
      (11): Upsample(scale_factor=2.0, mode='nearest')
      (12): Concat()
      (13): C3k2(
        (cv1): Conv(
          (conv): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (14): Upsample(scale_factor=2.0, mode='nearest')
      (15): Concat()
      (16): C3k2(
        (cv1): Conv(
          (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (17): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (18): Concat()
      (19): C3k2(
        (cv1): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (20): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (act): SiLU(inplace=True)
      )
      (21): Concat()
      (22): C3k2(
        (cv1): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(768, 512, kernel_size=(1, 1), stride=(1, 1))
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): C3k(
            (cv1): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (cv3): Conv(
              (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
              (act): SiLU(inplace=True)
            )
            (m): Sequential(
              (0): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
              (1): Bottleneck(
                (cv1): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
                (cv2): Conv(
                  (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                  (act): SiLU(inplace=True)
                )
              )
            )
          )
        )
      )
      (23): Detect(
        (cv2): ModuleList(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Conv(
              (conv): Conv2d(512, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (cv3): ModuleList(
          (0): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Sequential(
              (0): DWConv(
                (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=512)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): DWConv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (dfl): DFL(
          (conv): Conv2d(16, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
        )
      )
    )
  )
)

In [53]:
SEQ = Path(
    r"C:\Users\VAMSEEKRISHNA.P\Desktop\assignment\VisDrone2019-MOT-val\VisDrone2019-MOT-val\sequences\uav0000086_00000_v"
)


frames = sorted(
    SEQ.glob("*.jpg")
)


print(
    "Frames:",
    len(frames)
)

Frames: 464

In [56]:
def generate_tracking_video(
        model,
        output_name
):


    first = cv2.imread(
        str(frames[0])
    )


    h,w,_ = first.shape



    writer = cv2.VideoWriter(

        output_name,

        cv2.VideoWriter_fourcc(
            *"mp4v"
        ),

        30,

        (w,h)
    )



    trajectories = defaultdict(list)



    # reset tracker memory
    model.predictor = None



    total_time = 0



    for img_path in frames:



        frame = cv2.imread(
            str(img_path)
        )



        start = time.time()



        result = model.track(

            frame,

            imgsz=1280,

            conf=0.05,

            iou=0.5,

            classes=[0],

            tracker=r"Trackers\bytetrack_drone.yaml",

            persist=True,

            device=0,

            verbose=False

        )[0]



        end = time.time()


        fps = 1/(end-start)

        total_time += end-start




        if result.boxes.id is not None:



            ids = (
                result.boxes.id
                .cpu()
                .numpy()
            )


            boxes = (
                result.boxes.xyxy
                .cpu()
                .numpy()
            )




            for tid,box in zip(
                ids,
                boxes
            ):


                x1,y1,x2,y2 = map(
                    int,
                    box
                )



                cx = int(
                    (x1+x2)/2
                )

                cy = int(
                    (y1+y2)/2
                )



                trajectories[int(tid)].append(
                    (cx,cy)
                )


                # keep last 30 points
                trajectories[int(tid)] = (
                    trajectories[int(tid)][-30:]
                )




                # bbox
                cv2.rectangle(

                    frame,

                    (x1,y1),

                    (x2,y2),

                    (0,255,0),

                    2

                )



                # ID
                cv2.putText(

                    frame,

                    f"ID:{int(tid)}",

                    (x1,y1-5),

                    cv2.FONT_HERSHEY_SIMPLEX,

                    0.5,

                    (0,255,0),

                    2

                )



                # trajectory

                pts = np.array(
                    trajectories[int(tid)],
                    np.int32
                )


                if len(pts)>1:

                    cv2.polylines(

                        frame,

                        [pts],

                        False,

                        (0,0,255),

                        2

                    )




        # FPS display
        cv2.putText(

            frame,

            f"FPS:{fps:.1f}",

            (30,40),

            cv2.FONT_HERSHEY_SIMPLEX,

            1,

            (255,0,0),

            2

        )



        writer.write(
            frame
        )



    writer.release()



    print(
        output_name,
        "saved"
    )


    print(
        "Average FPS:",
        len(frames)/total_time
    )

In [57]:
generate_tracking_video(

    model_base,

    "YOLO11s_Base_ByteTrack.mp4"

)


generate_tracking_video(

    model_ft,

    "YOLO11s_FT_ByteTrack.mp4"

)

YOLO11s_Base_ByteTrack.mp4 saved
Average FPS: 32.35999716598519
YOLO11s_FT_ByteTrack.mp4 saved
Average FPS: 24.990883827591766

In [63]:
def generate_tracking_video(
        model,
        output_name
):


    first = cv2.imread(
        str(frames[0])
    )


    h,w,_ = first.shape



    writer = cv2.VideoWriter(

        output_name,

        cv2.VideoWriter_fourcc(
            *"avc1"
        ),

        30,

        (w,h)
    )



    trajectories = defaultdict(list)



    # reset tracker memory
    model.predictor = None



    total_time = 0



    for img_path in frames:



        frame = cv2.imread(
            str(img_path)
        )



        start = time.time()



        result = model.track(

            frame,

            imgsz=1280,

            conf=0.01,

            iou=0.5,

            max_det=1000,


            classes=[0],

            tracker=r"Trackers\bytetrack_drone.yaml",

            persist=True,

            device=0,

            verbose=False

        )[0]



        end = time.time()


        fps = 1/(end-start)

        total_time += end-start




        if result.boxes.id is not None:



            ids = (
                result.boxes.id
                .cpu()
                .numpy()
            )


            boxes = (
                result.boxes.xyxy
                .cpu()
                .numpy()
            )




            for tid,box in zip(
                ids,
                boxes
            ):


                x1,y1,x2,y2 = map(
                    int,
                    box
                )



                cx = int(
                    (x1+x2)/2
                )

                cy = int(
                    (y1+y2)/2
                )



                trajectories[int(tid)].append(
                    (cx,cy)
                )


                # keep last 30 points
                trajectories[int(tid)] = (
                    trajectories[int(tid)][-30:]
                )




                # bbox
                cv2.rectangle(

                    frame,

                    (x1,y1),

                    (x2,y2),

                    (0,255,0),

                    2

                )



                # ID
                cv2.putText(

                    frame,

                    f"ID:{int(tid)}",

                    (x1,y1-5),

                    cv2.FONT_HERSHEY_SIMPLEX,

                    0.5,

                    (0,255,0),

                    2

                )



                # trajectory

                pts = np.array(
                    trajectories[int(tid)],
                    np.int32
                )


                if len(pts)>1:

                    cv2.polylines(

                        frame,

                        [pts],

                        False,

                        (0,0,255),

                        2

                    )




        # FPS display
        cv2.putText(

            frame,

            f"FPS:{fps:.1f}",

            (30,40),

            cv2.FONT_HERSHEY_SIMPLEX,

            1,

            (255,0,0),

            2

        )



        writer.write(
            frame
        )



    writer.release()



    print(
        output_name,
        "saved"
    )


    print(
        "Average FPS:",
        len(frames)/total_time
    )

In [64]:
generate_tracking_video(

    model_base,

    "YOLO11s_Base_ByteTrack_avc1.mp4"

)


generate_tracking_video(

    model_ft,

    "YOLO11s_FT_ByteTrack_avc1.mp4"

)

YOLO11s_Base_ByteTrack_avc1.mp4 saved
Average FPS: 6.391565863260331
YOLO11s_FT_ByteTrack_avc1.mp4 saved
Average FPS: 5.678780631105903